---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.9.0
  interval: 1m0s
  storageNamespace: longhorn-system
  targetNamespace: longhorn-system
values:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn

