---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: replicator
  namespace: replicator
spec:
  chart:
    spec:
      chart: kubernetes-replicator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
      version: v2.12.1
  interval: 5m0s
  storageNamespace: replicator
  targetNamespace: replicator
  # install:
  #   crds: CreateReplace
  # upgrade:
  #   crds: CreateReplace