---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./user-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: sysyem-infrastructure
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets