---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-namespaces
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./namespaces
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-repositories
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 01-namespaces
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 03-secrets
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: secrets-repo  # References your private repo
  path: ./clusters/production  # Path within secrets repo
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age  # Your age key secret
  wait: true
  dependsOn:
    - name: 02-repositories

---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 04-crds
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 03-secrets
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 05-system-infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./system-infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 04-crds
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 06-system-infrastructure-configs
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./system-infrastructure/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 05-system-infrastructure-controllers
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 07-network-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./network-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 06-system-infrastructure-configs
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 08-user-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./user-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 07-network-infrastructure
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 09-apps
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 08-user-infrastructure
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets