---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./namespaces
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nkaz156/secrets
  ref:
    branch: main
  secretRef:
    name: secrets-repo-auth  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: secrets-repo  # References your private repo
  path: ./clusters/production  # Path within secrets repo
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age  # Your age key secret
  wait: true
  dependsOn:
    - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./system-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: secrets
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets