---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./namespaces
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nkaz156/secrets
  ref:
    branch: main
  secretRef:
    name: secrets-repo-auth
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: secrets-repo  # References your private repo
  path: ./clusters/production  # Path within secrets repo
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age  # Your age key secret
  wait: true
  dependsOn:
    - name: namespaces
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: secrets
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: repositories
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./system-infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: crds
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-infrastructure-configs
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  path: ./system-infrastructure/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: system-infrastructure-controllers
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
