---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
      version: 25.10.1
  interval: 10m0s
  storageNamespace: authentik
  targetNamespace: authentik
  valuesFrom:
    - kind: Secret
      name: authentik-postgres-user
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-postgres-user
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-creds
      valuesKey: authentik-secret
      targetPath: authentik.secret_key
  values:
    authentik:
      # secret_key: "" Value injected by flux from secret above
      error_reporting:
        enabled: false
      postgresql:
        host: authentik-postgresql-rw.authentik # Service.namespace
        name: authentik # db name
        # user: "" Set by flux
        # password: "" Set by flux
        port: 5432
      # email:
      #   # host: ""
      #   port: 587
      #   # username: ""
      #   # password: ""
      #   use_tls: true
      #   # from: ""
    # server:
    #   ingress:
    #     ingressClassName: traefik-prod-3
    #     enabled: true
    #     hosts:
    #       - authentik-prod-1.kube-prod-1.home.clcreative.de
    #     tls:
    #       - hosts:
    #           - authentik-prod-1.kube-prod-1.home.clcreative.de
    #         secretName: authentik-prod-1-tls
    postgresql:
      enabled: false # Disable Authentik's default postgres database
