---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      version: 2.34.0
  interval: 1h
  releaseName: pihole
  storageNamespace: pihole
  targetNamespace: pihole
  values:
    admin:
      existingSecret: pihole-creds
    image:
      repository: pihole/pihole
      tag: 2025.11.0
    dnsmasq:
      customDnsEntries:
        - address=/lenovo-01.home.arpa/192.168.100.1
        - address=/dell-01.home.arpa/192.168.100.2
        - address=/dell-02.home.arpa/192.168.100.3
        - address=/pihole.${INTERNAL_DOMAIN}/192.168.104.2

      customCnameEntries:
        # - cname=foo.nas,nas

    persistentVolumeClaim:
      enabled: true
      size: "1G"

    serviceWeb:
      # loadBalancerIP: 192.168.104.2
      # externalTrafficPolicy: 
      # annotations:
      #   "lbipam.cilium.io/ips": "192.168.104.2"
      # extraLabels: 
      #   serviceType: dns-admin
      https:
        enabled: false
      name: pihole-web
      type: ClusterIP

    serviceDns:
      loadBalancerIP: 192.168.104.1
      externalTrafficPolicy: Cluster
      annotations:
        "lbipam.cilium.io/ips": "192.168.104.1"
        "lbipam.cilium.io/sharing-key": "dns-ips"
      extraLabels: 
        cluster.home.arpa/service-type: dns
      type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: pihole-gateway
  namespace: pihole
spec:
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "192.168.104.2"
    labels:
      cluster.home.arpa/service-type: dns-admin
  gatewayClassName: cilium
  listeners:
  - name: pihole-https-listener
    protocol: HTTPS
    port: 443
    hostname: pihole.${INTERNAL_DOMAIN}
    tls:
      certificateRefs:
       - kind: Secret
         name: wildcard-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole-https-route
  namespace: pihole
spec:
  parentRefs:
  - name: pihole-gateway
    sectionName: pihole-https-listener
  hostnames:
  - "pihole.${INTERNAL_DOMAIN}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pihole-web
      port: 80
