---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0-202511030807-minimal-trixie@sha256:b5049f6187822761e6766e1135e224046eff09ee11aa5552976d2056c85a8806
  instances: 3
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: backup
        passwordSecret:
          name: postgres-backup-user
        login: true
        superuser: false
        inRoles:
          - pg_read_all_data
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-user
  storage:
    size: 2Gi
    storageClass: longhorn
  postgresql:
    parameters:
      max_connections: "200"  
      shared_buffers: "256MB"
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      version: 2025.10.1
  interval: 10m0s
  storageNamespace: authentik
  targetNamespace: authentik
  valuesFrom:
    - kind: Secret
      name: authentik-postgres-user
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-postgres-user
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-creds
      valuesKey: authentik-secret
      targetPath: authentik.secret_key
  values:
    authentik:
      # secret_key: "" Value injected by flux from secret above
      error_reporting:
        enabled: false
      postgresql:
        host: authentik-postgresql-rw.authentik # Service.namespace
        name: authentik # db name
        # user: "" Set by flux
        # password: "" Set by flux
        port: 5432
      # email:
      #   # host: ""
      #   port: 587
      #   # username: ""
      #   # password: ""
      #   use_tls: true
      #   # from: ""
    # server:
    #   ingress:
    #     ingressClassName: traefik-prod-3
    #     enabled: true
    #     hosts:
    #       - authentik-prod-1.kube-prod-1.home.clcreative.de
    #     tls:
    #       - hosts:
    #           - authentik-prod-1.kube-prod-1.home.clcreative.de
    #         secretName: authentik-prod-1-tls
    postgresql:
      enabled: false # Disable Authentik's default postgres database
